'use client';
import Image from 'next/image';
import { useRouter,useSearchParams } from 'next/navigation';
import { useTransition, useState, useOptimistic } from 'react';
import { ArrowRight, Search, MapPin, Utensils, BedDouble, Compass, Bus, BriefcaseMedical, LayoutGrid, Map, SlidersHorizontal, Info, RotateCw, Waves } from 'lucide-react';
import { Place, categories, labels } from '@/lib/types';
import { PlaceCard } from './card';
import { Button } from './ui/button';
import { LazyMap } from './lazy-map';
import { FadeContent } from './react-bits/fade-content';
const icons={gastronomia:Utensils,alojamiento:BedDouble,actividades:Compass,transporte:Bus,servicios:BriefcaseMedical};
export function Explore({places}:{places:Place[]}) {
 const router=useRouter(),params=useSearchParams();const [pending,start]=useTransition(); const [query,setQuery]=useState(params.get('q')||'');const rawCategory=params.get('category');const category=categories.find(c=>c===rawCategory)||'';const open=params.get('open')==='true';const [optimisticOpen,setOptimisticOpen]=useOptimistic(open);const map=params.get('view')==='map';
 function update(values:Record<string,string>){const next=new URLSearchParams(params.toString());Object.entries(values).forEach(([k,v])=>v?next.set(k,v):next.delete(k));start(()=>router.push(`/?${next}`,{scroll:false}));}
 return <main id="main"><section className="hero shell"><Image className="hero-image" src="https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=2000&q=85" alt="Paisaje verde de bosque junto al agua, imagen ilustrativa del litoral" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow"><MapPin size={14}/> PARANÁ, ENTRE RÍOS</span><FadeContent><h1>Tu próximo plan<br/>está <em>acá cerca.</em></h1></FadeContent><p>Descubrí los sabores, rincones y experiencias de Paraná.<br className="desktop"/> Todo lo que necesitás, en un mismo lugar.</p><form className="search-box" onSubmit={e=>{e.preventDefault();update({q:query});}}><Search size={22}/><input aria-label="Buscar lugares" placeholder="¿Qué te gustaría descubrir?" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><Button type="submit" disabled={pending}>Buscar <ArrowRight size={17}/></Button></form><div className="hero-foot"><Waves size={17}/><span>Un río. Mil formas de disfrutarlo.</span></div></div><span className="hero-caption">INSPIRACIÓN LITORAL <span>—</span> SALÍ A EXPLORAR</span></section>
 <section className="shell discovery" aria-label="Explorar lugares"><div className="category-row"><button className={`category ${!category?'selected':''}`} onClick={()=>update({category:''})}><LayoutGrid size={21}/><span>Todo para explorar</span></button>{categories.map(c=>{const Icon=icons[c];return <button key={c} className={`category ${category===c?'selected':''}`} aria-pressed={category===c} onClick={()=>update({category:c})}><Icon size={21}/><span>{labels[c]}</span></button>;})}</div>
 <div className="results-heading"><div><span className="section-kicker">ENCONTRÁ TU LUGAR</span><h2>{category?labels[category]:'Paraná te espera'}<span className="small-spark">✳</span></h2><p>Planes para cada momento, a tu manera.</p></div><div className="view-switch" aria-label="Vista de resultados"><button className={!map?'selected':''} aria-pressed={!map} onClick={()=>update({view:''})}><LayoutGrid size={16}/>Lista</button><button className={map?'selected':''} aria-pressed={map} onClick={()=>update({view:'map'})}><Map size={16}/>Mapa</button></div></div>
 <div className="filter-bar"><div className="filter-left"><SlidersHorizontal size={17}/><label className="open-filter"><input type="checkbox" checked={optimisticOpen} onChange={e=>{const checked=e.target.checked;start(()=>{setOptimisticOpen(checked);update({open:checked?'true':''});});}}/><span className="switch"/>Abierto ahora</label><span className="filter-divider"/><span className="result-count" aria-live="polite">{pending?'Buscando…':`${places.length} lugares para descubrir`}</span></div><Button variant="ghost" onClick={()=>start(()=>router.refresh())} disabled={pending} aria-label="Volver a consultar lugares"><RotateCw size={15}/><span className="desktop">Actualizar</span></Button></div>
 {(params.get('q')||category||open)&&<div className="active-filters"><span>{params.get('q')?`Búsqueda: “${params.get('q')}”`:'Filtros aplicados'}</span><button onClick={()=>{setQuery('');update({q:'',category:'',open:''});}}>Limpiar filtros ×</button></div>}
 <div aria-busy={pending} className={pending?'results pending':'results'}>{places.length===0?<div className="empty"><Search size={36}/><h3>No encontramos lugares con esos filtros</h3><p>Probá otra búsqueda o explorá todas las categorías.</p><Button onClick={()=>{setQuery('');update({q:'',category:'',open:''});}}>Ver todos los lugares</Button></div>:map?<LazyMap places={places}/>:<div className="cards-grid">{places.map(p=><PlaceCard key={p.id} place={p}/>)}</div>}</div>
 <div className="demo-notice"><Info size={18}/><p><strong>Estás explorando una demostración.</strong> Los establecimientos marcados como demo son ficticios y las fotos son ilustrativas. El estado es declarado por cada prestador y vence a las 24 horas.</p></div>
 </section></main>
}