import { writeFileSync } from 'node:fs';
import { demoPlaces } from '../lib/demo';
const quote=(v:string)=>`'${v.replaceAll("'","''")}'`;
const rows=demoPlaces.map((p,i)=>`(${[quote(p.id),quote(p.name),quote(p.description),quote(p.category),quote(p.address),p.latitude,p.longitude,quote(p.image_url),quote(JSON.stringify(p.hours))+'::jsonb',quote(p.status),quote(p.availability),`now() - interval '${i===5||i===10?48:2} hours'`,'true'].join(', ')})`);
const sql=`-- All businesses are fictional. Photos are illustrative.\n-- Generated by npm run seed:generate. Re-running does not overwrite owner changes.\ninsert into public.places (id,name,description,category,address,latitude,longitude,image_url,hours,status,availability,status_updated_at,is_demo) values\n${rows.join(',\n')}\non conflict (id) do nothing;\n`;
writeFileSync('supabase/seed.sql',sql);